### ISSUE TITLE
Graceful shutdown of Sink

### ISSUE THREAD

**Issue by yarelm** [google/go-metrics-stackdriver#15]
Hi. 
In some cases, there is a graceful shutdown logic of the application (such as in Cloud Run), and I need a way to gracefully shutdown the Sink as well, so pending metrics will get sent upon closure and not lost.

**Comment by tam7t** [comment]
Hm, we could expand `NewSink` could accept a context and flush/shutdown on context cancellation (since https://github.com/google/go-metrics-stackdriver/pull/16 is already a breaking change)

Or could add a `Flush()` method to `Sink` struct so that the caller could do something like`defer s.Flush()` or:

```
<-ctx.Done()
s.Flush()
```

(though flush itself should probably accept a context to add a deadline to the flush RPCs)

Or both

**Comment by yarelm** [comment]
Added #17 

This one is not a breaking change and solves this issue.

**Comment by tam7t** [comment]
Added this to a tagged release: https://github.com/google/go-metrics-stackdriver/releases/tag/v0.4.0
